2025-05-01 15:45:16,423 [INFO] make_new_files_for_run started
2025-05-01 15:45:19,665 [ERROR] Error inside make_new_files_for_run: [WinError 3] The system cannot find the path specified: ''
Traceback (most recent call last):
  File "C:\Users\stepo\Desktop\Thesis\GNU_styled\Generator.py", line 66, in make_new_files_for_run
    os.makedirs(domains_path, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
2025-05-01 15:46:36,175 [INFO] make_new_files_for_run started
2025-05-01 20:24:17,603 [INFO] make_new_files_for_run started
2025-05-01 20:26:27,102 [INFO] make_new_files_for_run started
2025-05-01 20:26:32,158 [ERROR] Error inside make_new_files_for_run: name 'np' is not defined
Traceback (most recent call last):
  File "C:\Users\stepo\Desktop\Thesis\GNU_styled\Generator.py", line 96, in make_new_files_for_run
    expression = np.random.randint(0, 50)
                 ^^
NameError: name 'np' is not defined
2025-05-01 20:27:11,047 [INFO] make_new_files_for_run started
2025-05-01 20:27:15,796 [ERROR] Error inside make_new_files_for_run: name 'np' is not defined
Traceback (most recent call last):
  File "C:\Users\stepo\Desktop\Thesis\GNU_styled\Generator.py", line 96, in make_new_files_for_run
    #expression = avg_expr * random.uniform(0.9, 1.1)
                 ^^
NameError: name 'np' is not defined
2025-05-01 20:28:01,361 [INFO] make_new_files_for_run started
2025-05-01 20:35:42,138 [INFO] make_new_files_for_run started
2025-05-01 22:11:43,700 [INFO] make_new_files_for_run started
2025-05-01 22:24:45,498 [INFO] make_new_files_for_run started
